spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/my_board?&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: root
    password: 1234
    mapper-locations: classpath:/mapper/**/*.xml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: c:\\upload

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  config-location: classpath:/mybatis/mybatis-config.xml